### ISSUE TITLE
URL action icon not showing

### ISSUE THREAD

**Issue by kzahel** [Rob--W/crxviewer#12] opened 2014-11-10 04:41 UTC
I just got a new chromebook (toshiba CB2), chrome is version 38.
For some reason the action icon (CRX logo) is not showing up for any in webstore URLs
Not sure what's going on here...

**Comment by Rob--W** [comment] 2015-08-16 09:49
The above bug was marked as a duplicate of https://code.google.com/p/chromium/issues/detail?id=461958, which was fixed in Chrome 43.

**Closed by Rob--W** 2015-08-16 09:49 UTC
Labels: bug
