### ISSUE TITLE
'Network error' since bug 1415644

### ISSUE THREAD

**Issue by Loirooriol** [Rob--W/crxviewer#58] opened 2018-03-30 15:53 UTC
In [bug 1415644](https://bugzilla.mozilla.org/show_bug.cgi?id=1415644) they added some restrictions and now Extension source viewer just shows a 'Network error' because it can't download the source code.

https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=f96e8d3c02251534d208bafb046d007970e284a5&tochange=39e131181d442409a5df2ed945c02aca2b9baca2

I tried clearing `extensions.webextensions.restrictedDomains` pref but strangely it didn't work.

**Comment by Rob--W** [comment] 2018-04-02 10:46
Thanks for the report. I have created an upstream bug report at: https://bugzilla.mozilla.org/show_bug.cgi?id=1450649

Hopefully that bug gets resolved. If not, then I would have to proxy the request through an external server, as I already do for the demo at https://robwu.nl/crxviewer :
https://github.com/Rob--W/crxviewer/blob/e0d63dae775980999aef4e925225a4e59ad5be10/src/crxviewer.js#L1547-L1556

**Comment by Mathnerd314** [comment] 2018-05-21 18:42
Looks like the Mozilla bug has been resolved as WONTFIX, so can you push the work-around to AMO?

**Comment by Rob--W** [comment] 2018-05-21 21:20
I have implemented a new work-around that does not have negative side effects, and published it as version 1.6.4 on AMO: https://addons.mozilla.org/en-US/firefox/addon/crxviewer/versions/1.6.4

**Closed by Rob--W** 2018-05-21 21:20 UTC

**Comment by Jackymancs4** [comment] 2018-06-05 18:44
Hello @Rob--W 
Does your workaround (c4a4d4e23e757d19cfa669edb5f446e28f427e1f) only affect the viewer?
Because it seems impossible to me to directly download the sources of any Addons from both the UI and the location bar icon, and the error is exactly Network error.

<img width="1280" alt="Error" src="https://user-images.githubusercontent.com/6209647/40996016-1241fb16-6901-11e8-9f97-18fd2f3791e8.png">

**Comment by Rob--W** [comment] 2018-06-05 21:17
@Jackymancs4 Try the new version ;)

**Comment by Jackymancs4** [comment] 2018-06-05 23:16
Confirmed 1.6.5 work like a charm 👍 
Thank you for the light-speed fix&release!
