### ISSUE TITLE
Network error when trying to load AMO addons

### ISSUE THREAD

**Issue by mymindstorm** [Rob--W/crxviewer#64] opened 2018-05-16 03:16 UTC
Problem:
``` 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons.mozilla.org/firefox/downloads/latest/crxviewer/platform:2/crxviewer.xpi. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
```

I'm running Firefox 60.0 on Fedora 28, CRX Viewer version 1.6.3

**Comment by Rob--W** [comment] 2018-05-16 09:35
Duplicate of #58.

**Closed** 2018-05-16 09:35 UTC
