### ISSUE TITLE
Support for Microsoft Edge Chromium Addons

### ISSUE THREAD

**Issue by 2Seven72** [Rob--W/crxviewer#114] opened 2022-02-25 02:59 UTC
Hi,
Could you please add support for Microsoft Edge Addons in the next revision of Extension Source Viewer?

Greetings and Thanks ;)

**Comment by yfdyh000** [comment] 2022-02-26 19:19
dupe of #43

**Comment by 2Seven72** [comment] 2022-02-27 04:02
Very nice, Thank You

**Comment by 2Seven72** [comment] 2022-02-27 04:07
Very nice, thank you ;)

**Comment by 2Seven72** [comment] 2022-02-27 04:16
> dupe of #43

Very nice, thank you ;)

**Comment by Rob--W** [comment] 2022-03-19 21:29
This has been implemented (#43), I'll publish a new version shortly.

**Comment by 2Seven72** [comment] 2022-03-19 23:23
Thank You so much ;)

**Comment by Rob--W** [comment] 2022-03-28 05:09
I have submitted version 1.6.12 to Firefox's add-on gallery, the Chrome Web Store and Opera's addon gallery. That version includes support for viewing Edge extensions.

**Closed by Rob--W** 2022-03-28 05:09 UTC
