### ISSUE TITLE
[Feature Request] Add support for Edge Chromium extensions

### ISSUE THREAD

**Issue by BananaManCJ** [Rob--W/crxviewer#95] opened 2020-06-23 18:08 UTC
I am having trouble figuring out the download links, but will update this issue if I figure it out

**Comment by Rob--W** [comment] 2020-06-23 21:17
Kind of duplicate of https://github.com/Rob--W/crxviewer/issues/43 .

**Closed** 2022-03-28 05:07 UTC
